#!/bin/sh -e

TOOL_CMD=pylint
PATH=$(basename $0)/utils:$PATH
CONFIG_PATH="$(dirname $0)/default_configs/pylintrc"
FILES=$(git ls-files '*.py')

echo "** Running $TOOL_CMD (using config from $CONFIG_PATH)..."
python3 -m pylint --rcfile=$CONFIG_PATH $FILES
