#!/usr/bin/env python3
import os
import shutil
import sys


def print_usage():
    print(f"Usage: {sys.argv[0]} [--] COMMAND")

def main():
    if len(sys.argv) < 2:
        print_usage()
        return -1
    result = shutil.which(sys.argv[1])
    if result is None:
        print(f"{os.path.abspath(sys.argv[0])}: no {sys.argv[1]} in {os.environ['PATH']}")
        return -1
    print(result)
    return 0

if __name__ == '__main__':
    sys.exit(main())
